Repository aredn/aredn, pull requests merged in 2025-07, with the labels that each got.

#2291 Dont preserve babel state across upgrades
  files/etc/arednsysupgrade.conf
  files/usr/local/bin/aredn_sysupgrade
Labels: legacy build

#2298 Revert "Dont preserve babel state across upgrades"
  files/etc/arednsysupgrade.conf
  files/usr/local/bin/aredn_sysupgrade
Labels: babel build

#2300 Speed up status page by avoiding dns lookups.
  files/app/partial/local-and-neighbor-devices.ut
Labels: legacy build

#2303 Add support for Heltec H7608 (HaLow device)
  SUPPORTED_DEVICES.md
  patches/790-morsemicro-support.patch
Labels: babel build

#2305 Improve UI around local service proxies
  Makefile
  configs/common.config
  files/app/main/status/e/local-services.ut
  files/app/main/videoproxy.ut
  files/app/resource/css/admin.css
Labels: babel build

#2306 Common validation of the URLs passed to the various proxy urls.
  files/app/main/httpproxy.ut
  files/app/main/redirect.ut
  files/app/main/videoproxy.ut
  files/usr/share/ucode/aredn/network.uc
Labels: babel build

#2309 Add a TODO for ffmpeg
  files/usr/share/ucode/aredn/messages.uc
Labels: babel build

#2312 Quiet failed message pings.
  files/usr/local/bin/aredn_message.sh
Labels: legacy build

#2314 Fix package url validator
  files/app/main/status/e/packages.ut
Labels: babel build

#2316 Improve URL parser.
  files/app/resource/js/meshpage.js
  files/usr/share/ucode/aredn/network.uc
Labels: babel build

#2318 Add a few more service templates.
  files/app/main/status/e/local-services.ut
  files/app/resource/css/user.css
Labels: babel build

#2321 Improve UI around video proxy.
  files/app/main/status/e/local-services.ut
  files/usr/share/ucode/aredn/hardware.uc
  files/usr/share/ucode/aredn/messages.uc
Labels: babel build

#2319 Fix broken build.
  configs/common.config
  configs/ipq40xx-generic.config
  configs/ipq40xx-mikrotik.config
  configs/mediatek-filogic.config
  configs/x86-64.config
Labels: babel build

#2323 Add webapp manifest support.
  files/app/main/app.ut
  files/app/resource/img/favicon.ico.gz
  files/app/resource/manifest.json
  files/app/root.ut
Labels: babel build

#2325 Fix math for generaring M9 channel numbers.
  files/usr/share/ucode/aredn/hardware.uc
Labels: legacy build

#2326 Fix math for generaring M9 channel numbers.
  files/usr/share/ucode/aredn/hardware.uc
Labels: babel build

#2327 Add cloud and map shortcuts to manifest
  files/app/main/cloud.ut
  files/app/main/map.ut
  files/app/partial/nav-status.ut
  files/app/resource/manifest.json
Labels: babel build

#2328 Fix dhcp options
  files/usr/local/bin/node-setup
Labels: babel build

#2330 Fix parsing of tagged options
  patches/704-dnsmasq-fixes.patch
Labels: legacy build, openwrt bug

#2332 Add cloud and map pages to webapp
  files/app/main/app.ut
  files/app/partial/cloud.ut
  files/app/partial/map.ut
  files/app/partial/mesh.ut
  files/app/partial/nav.ut
  files/app/partial/selection.ut
  files/app/resource/css/user.css
  files/app/root.ut
Labels: babel build

#2333 add support for NanoStation AC loco
  SUPPORTED_DEVICES.md
  configs/ath79-generic.config
  files/etc/radios.json
  patches/755-ubiquiti-ac-loco.patch
Labels: new hardware support

#2335 Support for NanoStation AC Loco (from formtapez)
  SUPPORTED_DEVICES.md
  configs/ath79-generic.config
  files/etc/radios.json
  patches/755-ubiquiti-ac-loco.patch
  patches/series
Labels: new hardware support, babel build

#2337 Improve video proxy error handling.
  files/app/main/videoproxy.ut
Labels: babel build

#2344 Fix arednlink data in support file
  files/usr/share/ucode/aredn/configuration.uc
Labels: legacy build

#2346 Bump resource class to avoid build timeouts
  .circleci/config.yml
Labels: babel build

#2349 Fix job name
  .circleci/config.yml
Labels: babel build

#2350 Add missing paths
  .circleci/config.yml
Labels: babel build

#2352 Persist entire project in workspace
  .circleci/config.yml
Labels: babel build

#2353 Update circleci for main
  .circleci/config.yml
Labels: legacy build

#2354 Fix Morse builds in main
  .circleci/config.yml
Labels: legacy build

#2357 Improve slack version number (missing a final digit)
  .circleci/config.yml
Labels: babel build

#2358 Improve slack version number (missing a final digit)
  .circleci/config.yml
Labels: legacy build

#2360 Restore CircleCI timeouts
  .circleci/config.yml
Labels: legacy build
